# SITE SETTINGS
title: "C. Vladimir Rodríguez Caballero"
name: "C. Vladimir Rodríguez Caballero"
description: "Researcher in applied econometrics, time series, climate economics and financial econometrics."
url: "https://vlasmetrics7.github.io"

# THEME
theme: null
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Enable dropdown menus in the top navigation
minimal_mistakes_skin: default


# AUTHOR
author:
  name: "Vladimir Rodríguez Caballero"
  avatar: "/assets/images/profile.jpg"
  bio: "Assistant Professor of Economics. Research in econometrics, macro-finance, and climate impacts."
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/vlasmetrics7"

# COLLECTIONS
collections:
  publications:
    output: true
  teaching:
    output: true
  projects:
    output: true

# NAVIGATION
include: ["_pages"]
  
# MARKDOWN
markdown: kramdown

# PLUGINS
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap



